src/build.props
Diff doesn't show it, but this file was not properly persisted as UTF8.
@lgolding fyi. This is the final blocker to nuget update, so pushing forward.
=> Fix unicode character substitution

appveyor.yml
It was still using the address from our old team.
=> Update AppVeyor notification email address.

src/Json.Schema.ToDotNet.Cli/Json.Schema.ToDotNet.Cli.csproj
When you run the ToDotNet command line app, it fails because it can't find the resource stream. Somehow the `.resx` and the `.Resources.designer` files got separated in the project file. Fix the project file to connect the resources back up.
=> Fix #39: ToDotNet application can't find its resources

src/Json.Schema.ToDotNet.UnitTests/Hints/ClassNameHintTests.cs
In this scenario, the code generator isn't as easy to use as it should be. You need to file any hints that affect the renamed class _under the new class name_. For example, your `CodeGenHints.json` might look like this:
```
"exception": [
{
"kind": "ClassNameHint",
"arguments": {
"className": "ExceptionData"
}
}
],
"exceptionData": [
{
"kind": "BaseTypeHint",
"arguments": {
"baseTypeNames": [
"PropertyBagHolder"
]
}
}
],
```
Another nit in the design is that the renamed class has to appear in camelCase in the hints file. In the example above, note that the dictionary key is `exceptionData`, even though the renamed class is `ExceptionData`.
This PR just adds a unit test to demonstrate this usage.
=> Add unit test to demonstrate interaction of ClassNameHint with other hints

src/Json.Schema.ToDotNet.UnitTests/DataModelGeneratorTests.cs, src/Json.Schema.ToDotNet/ClassGenerator.cs, src/Json.Schema.ToDotNet/ClassOrInterfaceGenerator.cs, src/Json.Schema.ToDotNet/EqualityComparerGenerator.cs, src/Json.Schema.ToDotNet/InterfaceGenerator.cs, src/Json.Schema.ToDotNet/Json.Schema.ToDotNet.csproj, src/Json.Schema.ToDotNet/PropertyInfo.cs, src/Json.Schema.ToDotNet/PropertyInfoDictionary.cs, src/Json.Schema.ToDotNet/Resources.Designer.cs, src/Json.Schema.ToDotNet/Resources.resx, src/Json.Schema.ToDotNet/RewritingVisitorGenerator.cs, src/Json.Schema.ToDotNet/SyntaxNodeExtensions.cs, src/Json.Schema.ToDotNet/TypeGenerator.cs, src/Json.Schema.UnitTests/JsonSchemaTests.cs, src/Json.Schema/JsonSchema.cs
#57: When a schema property declares a default value, assign that value to the property in the default constructor. This ensures that the property has the correct default even if you construct the object by hand rather than by deserializing it from JSON.
#58: When a schema property declares a default value, decorate the property with a `System.ComponentModel.DefaultValue` attribute. This avoids your having to specify those attributes in the CodeGenHints.json file, which is error-prone.
Also:
- Fix a bug where the generated doc comments for properties had an extra space: `cref="P: propName`" &rarr; `cref="P:propName`".
- Address some hygiene-related IDE messages by marking some properties `readonly`, and by inlining the declarations of some `out` parameters.
=> Fix #57, fix #58: Emit initializers and attributes for default values

src/build.props
@lgolding 
NuGet now allows referencing fixed license versions. These can be shipped in the package itself. NuGet packaging tools also have built-in understanding of standard licenses, such as the MIT license. Using PackageLicenseExpression to refer to MIT produces a new nuspec <license> element. NuGet packaging tools also provides a licenseUrl that points to the official hosted version of this license.
This change is required to submit to NuGet for Microsoft packages.
=> Update licensing reference to satisfy NuGet improvements in this area.

BuildAndTest.ps1, src/Json.Schema.ToDotNet.Cli/Json.Schema.ToDotNet.Cli.nuspec, src/Json.Schema.Validation.Cli/Json.Schema.Validation.Cli.nuspec, src/build.props
This change fixes a problem with certain jschema packages which prevented them from being published, because they violated Microsoft package publishing policy (PPP, if you like ;-)). Opportunistically, it fixes a couple of other package property problems (PPP2, if you like).
Our build.props file sets the `<PackageLicenseExpression>` property to `Apache-2.0`. The creation of the JsonPointer and JsonSchema NuGet packages is done by `dotnet pack`, and is driven by the MSBuild project file. So those packages respected the package license expression, and picked up the correct license.
But the NuGet packages for the two command line tools (ToDotNet and Validator) are created by directly invoking NuGet.exe on custom .nuspec files. This is necessary because those packages require files that are …
=> Fix #68, fix #69: Use packageLicenseExpression in all packages, and fix some package properties

src/build.props
FYI, based on testing, the Authors element always flows to Owners. NuGet is rejecting authors that contains anything other than 'Microsoft'. We appear to need to strictly reference MS for both Authors and Owners. 
Presumably. I will try this and if it fails will consult with NuGet team later this week.
@lgolding
=> Set owners and authors strictly to Microsoft

src/Json.Schema.ToDotNet.UnitTests/DataModelGeneratorTests.cs, src/Json.Schema.ToDotNet.UnitTests/TestData/Array.schema.json, src/Json.Schema.ToDotNet/PropertyInfoDictionary.cs, src/ReleaseHistory.md, src/build.props
If a property has `"type": "array"` and `"items"` is missing, then `"items`" is equivalent to an empty schema, meaning it can hold anything. In this case, produce a .NET array element type of `object`.
=> Fix #108: Crash if property type is "array" and "items" is absent.

src/Json.Schema/UriOrFragment.cs
Found a bug while trying to load some schemas with relative refs in a union. Fails with a UriFormatException.
=> Fixed the copy constructor to allow for relative refs

BuildAndTest.ps1, CreateSigningDirectory.cmd, PushSignedBinariesIntoBuild.cmd, azure-pipelines.yml, src/Everything.sln, src/Json.Pointer.UnitTests/Json.Pointer.UnitTests.csproj, src/Json.Schema.PerformanceTests/Json.Schema.PerformanceTests.csproj, src/Json.Schema.ToDotNet.Cli/Json.Schema.ToDotNet.Cli.nuspec, src/Json.Schema.Validation.Cli/Json.Schema.Validation.Cli.nuspec, src/ReleaseHistory.md
This change is updating the following:
- azure pipelines to point to vs2022 folder
- scripts to use `netcoreapp3.1` folders instead of `netcoreapp2.x`
Once this gets merged, we should publish a new version (1.1.3), which will release a new version with supported client tools.
=> Migrating to netcoreapp3.1

src/Json.Schema.Validation.Cli/Json.Schema.Validation.Cli.csproj, src/Json.Schema.Validation.Cli/Program.cs, src/Json.Schema.Validation.UnitTests/Json.Schema.Validation.UnitTests.csproj, src/Json.Schema.Validation.UnitTests/TestData/ComprehensiveInstanceFile-validation-expected.sarif, src/Json.Schema.Validation/Json.Schema.Validation.csproj, src/ReleaseHistory.md, src/build.props
1. Update validator to use latest SARIF SDK (2.4.14)
2. I see SDK 2.3.3->2.4.14 have minor difference on the generated sarif for test input, fix the test with current output.
=> Update validator to use latest SARIF SDK (2.4.14)

src/ReleaseHistory.md, src/build.props
* Updating [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/13.0.1) from v9.0.1 to v13.0.1 in response to [Advisory: Improper Handling of Exceptional Conditions in Newtonsoft.Json](https://github.com/advisories/GHSA-5crp-9r3c-p9vr). [#155](https://github.com/microsoft/jschema/pull/155)
=> Releasing 1.1.5

src/Json.Pointer/Json.Pointer.csproj, src/Json.Schema.ToDotNet.Cli/Program.cs, src/Json.Schema.ToDotNet.UnitTests/Json.Schema.ToDotNet.UnitTests.csproj, src/Json.Schema.ToDotNet/Json.Schema.ToDotNet.csproj, src/Json.Schema/Json.Schema.csproj, src/ReleaseHistory.md
The is the same action as the SARIF SDK to "loosen min version requirement to 6.0.8 for .NET FX, 9.0.1 otherwise".
The jschema project is not on .NET FX, so we are using v9.0.1
Before it was upgraded to v13.0.1, it was on v9.0.1
so the change should be minimum impact, which is a basically a revert.
=> Loosen Newtonsoft.JSON minimum version requirement from v13.0.1 to v9.0.1

src/ReleaseHistory.md, src/build.props
* Loosen Newtonsoft.JSON minimum version requirement from v13.0.1 to v9.0.1 [Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/9.0.1). [#157](https://github.com/microsoft/jschema/pull/157)
* FEATURE: Add support for JSON Schema type `uuid`. [#132](https://github.com/microsoft/jschema/pull/132)
* FEATURE: Add new option for specifying .NET type to express Json integers: `--generate-json-integer-as = int | long | biginteger | auto` with a default of `int`. [#158](https://github.com/microsoft/jschema/pull/158)
=> Releasing 2.0.0

src/Json.Schema.ToDotNet.UnitTests/DataModelGeneratorTests.cs, src/Json.Schema.ToDotNet.UnitTests/TestData/Uuid.schema.json, src/Json.Schema.ToDotNet/PropertyInfoDictionary.cs, src/ReleaseHistory.md
This add feature to generate  `Guid?` when the `uuid` property is not required , and  `Guid` when it is.
Without this, for those using C# `string` was able to use C# `null`; but not now with the newly added C# `Guid` type.
=> Support Nullable Guid

src/Json.Schema.ToDotNet.UnitTests/DataModelGeneratorTests.cs, src/ReleaseHistory.md, src/build.props
* FEATURE: Add support for JSON Schema type `uuid` generate as C# nullable `Guid?`. [#164](https://github.com/microsoft/jschema/pull/164)
=> Releasing 2.1.0

src/Json.Schema.ToDotNet.UnitTests/DataModelGeneratorTests.cs, src/Json.Schema.ToDotNet.UnitTests/Hints/AttributeHintTests.cs, src/Json.Schema.ToDotNet.UnitTests/Hints/InterfaceHintTests.cs, src/Json.Schema.ToDotNet.UnitTests/Hints/PropertyModifiersHintTests.cs, src/Json.Schema.ToDotNet/PropertyInfoDictionary.cs, src/ReleaseHistory.md
Purpose of this change:
Ran through SARIF SDK looks good to remove all those:
`// NOTYETAUTOGENERATED: Property should be nullable int. https://github.com/Microsoft/jschema/issues/112`
https://github.com/Microsoft/jschema/issues/112
And also nullable `BigInteger`. 
Modified existing test case, and add a test in `GeneratesAttributesForPropertiesOfPrimitiveTypeWithDefaults()`
=> * BREAKING: .NET type to express Json integers now will be nullable if the property is not required and also without default.

src/Json.Schema.ToDotNet.UnitTests/DataModelGeneratorTests.cs, src/ReleaseHistory.md, src/build.props
* BREAKING: .NET type to express Json integers now will be nullable if the property is not required and also without default. [#167](https://github.com/microsoft/jschema/pull/167)
* FEATURE: Add new option for specifying .NET type to express Json numbers: `--generate-json-number-as = double | float | decimal` with a default of `double`. [#166](https://github.com/microsoft/jschema/pull/166)
=> Releasing 2.2.0

src/Json.Schema.Validation.UnitTests/ValidatorTests.cs, src/Json.Schema.Validation/RuleFactory.cs, src/Json.Schema.Validation/RuleResources.Designer.cs, src/Json.Schema.Validation/RuleResources.resx, src/Json.Schema.Validation/Validator.cs, src/Json.Schema/ErrorNumber.cs
Added string format validation for date-time, uri, uri-reference and uuid
Added error-messages and localization keys in English
Updated test cases to test validation for the format attribute
Tagging @shaopeng-gh and @michaelcfanning  for review
For example - The following schema validates the date-time format string value.
"String: format: valid with date-time format constraints",
@"{
""type"": ""string"",
""format"": ""date-time""
}",
"\"2023-02-03T12:34:56.789Z\""
=> Added support to validate Json against string format attribute from JSON Schema

src/ReleaseHistory.md, src/build.props
* FEATURE: Added support to validate JSON against string format attribute from JSON Schema. [#169](https://github.com/microsoft/jschema/pull/169)
=> releasing v2.3.0

src/Json.Schema.ToDotNet.UnitTests/Hints/PropertyNameHintTests.cs, src/Json.Schema.ToDotNet/PropertyInfoDictionary.cs, src/ReleaseHistory.md
BUG: Hint file should be consistent and use Pascal case. 
Fix `PropertyNameHint` not functional when Pascal case is used.
I can see most of our hint file definition use Pascal case: `Parent1.Child1`. If this is not correct, let me know.
Without this fix, hint file definition will need to use `Parent1.child1` to be functional.
There could be other places having the same case issue. Let me know if this fix is correct I can search and fix if there are any others.
=> Fix `PropertyNameHint` not functional when Pascal case is used.
